<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Unidad 3: Exploración, diagnóstico y limpieza de datos – Introducción al lenguaje R + RStudio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./unidad3.html">Unidad 3: Exploración, diagnóstico y limpieza de datos</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/logos_ine.svg" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./images/logos_ine.svg" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Temario</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidad1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unidad 1: Introducción al lenguaje R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidad2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unidad 2: Procesamiento de datos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidad3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Unidad 3: Exploración, diagnóstico y limpieza de datos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidad4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unidad 4: Tratamiento de datos específicos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidad5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unidad 5: Estadísticos, operaciones múltiples y resúmenes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidad6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unidad 6: Inferencia estadística</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidad7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unidad 7: Visualización de datos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidad8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unidad 8: Comunicar con Quarto</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./extra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extra: Control de flujo y funciones</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenidos</h2>
   
  <ul>
  <li><a href="#exploración-y-diagnóstico-de-datos" id="toc-exploración-y-diagnóstico-de-datos" class="nav-link active" data-scroll-target="#exploración-y-diagnóstico-de-datos">Exploración y diagnóstico de datos</a></li>
  <li><a href="#exploración-de-datos" id="toc-exploración-de-datos" class="nav-link" data-scroll-target="#exploración-de-datos">Exploración de datos</a></li>
  <li><a href="#comprobación-y-coerción-de-tipos-de-datos" id="toc-comprobación-y-coerción-de-tipos-de-datos" class="nav-link" data-scroll-target="#comprobación-y-coerción-de-tipos-de-datos">Comprobación y coerción de tipos de datos</a></li>
  <li><a href="#skimr" id="toc-skimr" class="nav-link" data-scroll-target="#skimr">Skimr</a></li>
  <li><a href="#dlookr" id="toc-dlookr" class="nav-link" data-scroll-target="#dlookr">dlookr</a>
  <ul class="collapse">
  <li><a href="#diagnose" id="toc-diagnose" class="nav-link" data-scroll-target="#diagnose">diagnose()</a></li>
  <li><a href="#diagnose_category" id="toc-diagnose_category" class="nav-link" data-scroll-target="#diagnose_category">diagnose_category()</a></li>
  <li><a href="#diagnose_numeric" id="toc-diagnose_numeric" class="nav-link" data-scroll-target="#diagnose_numeric">diagnose_numeric()</a></li>
  </ul></li>
  <li><a href="#diagnose_outlier" id="toc-diagnose_outlier" class="nav-link" data-scroll-target="#diagnose_outlier">diagnose_outlier()</a></li>
  <li><a href="#plot_outlier" id="toc-plot_outlier" class="nav-link" data-scroll-target="#plot_outlier">plot_outlier()</a>
  <ul class="collapse">
  <li><a href="#otras-funciones-del-paquete" id="toc-otras-funciones-del-paquete" class="nav-link" data-scroll-target="#otras-funciones-del-paquete">Otras funciones del paquete</a></li>
  </ul></li>
  <li><a href="#depuración-de-datos" id="toc-depuración-de-datos" class="nav-link" data-scroll-target="#depuración-de-datos">Depuración de datos</a></li>
  <li><a href="#gestión-de-duplicados" id="toc-gestión-de-duplicados" class="nav-link" data-scroll-target="#gestión-de-duplicados">Gestión de duplicados</a>
  <ul class="collapse">
  <li><a href="#eliminación-de-duplicados-por-observaciones-únicas" id="toc-eliminación-de-duplicados-por-observaciones-únicas" class="nav-link" data-scroll-target="#eliminación-de-duplicados-por-observaciones-únicas">Eliminación de duplicados por observaciones únicas</a></li>
  <li><a href="#eliminación-de-duplicados-por-recorte-de-observaciones" id="toc-eliminación-de-duplicados-por-recorte-de-observaciones" class="nav-link" data-scroll-target="#eliminación-de-duplicados-por-recorte-de-observaciones">Eliminación de duplicados por recorte de observaciones</a></li>
  <li><a href="#marcar-duplicados" id="toc-marcar-duplicados" class="nav-link" data-scroll-target="#marcar-duplicados">Marcar duplicados</a></li>
  </ul></li>
  <li><a href="#datos-faltantes-o-perdidos" id="toc-datos-faltantes-o-perdidos" class="nav-link" data-scroll-target="#datos-faltantes-o-perdidos">Datos faltantes o perdidos</a></li>
  <li><a href="#detectar-observaciones-incompletas-valores-missing" id="toc-detectar-observaciones-incompletas-valores-missing" class="nav-link" data-scroll-target="#detectar-observaciones-incompletas-valores-missing">Detectar observaciones incompletas (valores missing)</a></li>
  <li><a href="#gestión-de-nas-con-naniar" id="toc-gestión-de-nas-con-naniar" class="nav-link" data-scroll-target="#gestión-de-nas-con-naniar">Gestión de NA’s con naniar</a></li>
  <li><a href="#reemplazo-de-valores" id="toc-reemplazo-de-valores" class="nav-link" data-scroll-target="#reemplazo-de-valores">Reemplazo de valores</a></li>
  <li><a href="#eliminación-de-valores-na" id="toc-eliminación-de-valores-na" class="nav-link" data-scroll-target="#eliminación-de-valores-na">Eliminación de valores NA</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Otros formatos</h2><ul><li><a href="unidad3.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Unidad 3: Exploración, diagnóstico y limpieza de datos</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="unidad3.pdf" class="btn btn-primary">Descargar este documento en PDF</a></p>
<p>En el ámbito de los proyectos de análisis de datos, el preprocesamiento, también conocido como preparación de datos, es una etapa crucial que precede al análisis propiamente dicho. Esta fase esencial tiene como objetivo acondicionar los datos para su posterior análisis, garantizando su confiabilidad e integridad.</p>
<p>Las tareas de preprocesamiento son específicas para cada conjunto de datos y dependen de los objetivos del proyecto y las técnicas de análisis que se emplearán. Sin embargo, existen tareas comunes que son aplicables a la mayoría de los casos, entre las que se encuentran el diagnóstico y la limpieza de datos.</p>
<section id="exploración-y-diagnóstico-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="exploración-y-diagnóstico-de-datos">Exploración y diagnóstico de datos</h2>
<p>La etapa de diagnóstico de datos es fundamental para comprender la estructura y características del conjunto de datos que se va a analizar. Esta fase involucra una serie de tareas esenciales, como:</p>
<p><strong>Análisis de la estructura de la tabla de datos</strong>: Esta tarea implica comprender la organización de los datos, identificando las variables, sus tipos de datos y la distribución de los registros. Es relevante vincular este proceso con el “diccionario de datos” de la tabla o base, ya sea de fuente secundaria o creada por nosotros mismos.</p>
<p><strong>Verificación del tipo de dato de cada variable de interés</strong>: Es crucial determinar el tipo de dato de cada variable (numérica, categórica, fecha-hora, etc.) para aplicar las técnicas de análisis adecuadas.</p>
<p><strong>Detección de valores faltantes</strong>: La presencia de valores faltantes puede afectar significativamente los resultados del análisis. Es importante identificar estos valores y determinar la mejor manera de manejarlos (eliminación, imputación, etc.).</p>
<p><strong>Identificación de las categorías de las variables cualitativas</strong>: En el caso de variables categóricas, es necesario identificar las categorías existentes y evaluar su distribución.</p>
<p><strong>Análisis de los mínimos y máximos de valores de cada variable cuantitativa</strong>: Para variables numéricas, es importante determinar los valores mínimos y máximos para detectar posibles valores atípicos o errores de entrada.</p>
</section>
<section id="exploración-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="exploración-de-datos">Exploración de datos</h2>
<p>El primer paso en la exploración de un conjunto de datos es conocer su estructura y tamaño.</p>
<p>El tamaño está definido por la cantidad de observaciones (filas) y la cantidad de variables (columnas).</p>
<p>Llamamos estructura a la forma en se organizan sus variables, sus tipos de datos y sus categorías/valores.</p>
<p>Vamos a utilizar un dataframe de ejemplo con variedad en sus tipos de datos. Para ver su estructura en R base tenemos la función <code>str()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   74 obs. of  7 variables:
 $ id     : int  1 2 3 4 5 6 7 8 9 10 ...
 $ sexo   : chr  "M" "M" "M" "M" ...
 $ edad   : num  76 68 50 49 51 68 70 64 60 57 ...
 $ peso   : num  71 71 79 71 87 75 80 83 69 73 ...
 $ talla  : num  167 164 164 164 168 ...
 $ trabaja: logi  FALSE FALSE FALSE TRUE TRUE FALSE ...
 $ fecha  : Date, format: "2020-10-20" "2020-10-20" ...</code></pre>
</div>
</div>
<p>Nos informa que la tabla tiene 74 observaciones y 7 variables con su tipo de dato al lado.</p>
<p>En R base los tipos de datos son:</p>
<ul>
<li><strong>int</strong> (integer): números enteros</li>
<li><strong>num</strong> (numeric): números reales</li>
<li><strong>chr</strong> (character): caracteres (texto)</li>
<li><strong>logi</strong> (logical): valores lógicos</li>
<li><strong>Date</strong>: fechas</li>
<li><strong>fct</strong> (factor): factores</li>
</ul>
<p>En tidyverse, la función que reemplaza a str() es <code>glimpse()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(datos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 74
Columns: 7
$ id      &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…
$ sexo    &lt;chr&gt; "M", "M", "M", "M", "M", "M", "M", "M", NA, "F", "F", "M", "F"…
$ edad    &lt;dbl&gt; 76, 68, 50, 49, 51, 68, 70, 64, 60, 57, 83, 76, 27, 34, 17, 45…
$ peso    &lt;dbl&gt; 71.0, 71.0, 79.0, 71.0, 87.0, 75.0, 80.0, 83.0, 69.0, 73.0, 60…
$ talla   &lt;dbl&gt; 167.0, 164.0, 164.0, 164.0, 167.5, 170.0, 166.0, 160.0, 160.0,…
$ trabaja &lt;lgl&gt; FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, NA, TRUE, TRUE, TRUE, …
$ fecha   &lt;date&gt; 2020-10-20, 2020-10-20, 2020-10-20, 2020-11-05, 2020-11-05, 2…</code></pre>
</div>
</div>
<p>Parece idéntica pero tiene una ventaja cuando la tabla de datos tiene muchas variables. La lista de respuesta de str() se trunca y no nos deja visualizar la totalidad de columnas, cosa que si hace glimpse().</p>
<p>Por otra parte vamos a encontrar distintas definiciones para los tipos de datos, del modo tidyverse:</p>
<ul>
<li>num para a ser <strong>dbl</strong> (double): números reales</li>
<li>logi para a ser <strong>lgl</strong> (logical): valores lógicos</li>
</ul>
<p>Y se incluyen un tipo nuevo:</p>
<ul>
<li><strong>dttm</strong> (date-time): fechas y horas</li>
</ul>
<p>Esta exploración inicial de la estructura generalmente viene acompañada por el “diccionario de datos” (codebook) asociado a la tabla de datos, ya sea que esta tabla provenga de un proyecto de investigación propio (fuente primaria), producto de una fuente secundaria o de un sistema de vigilancia epidemiológica.</p>
</section>
<section id="comprobación-y-coerción-de-tipos-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="comprobación-y-coerción-de-tipos-de-datos">Comprobación y coerción de tipos de datos</h2>
<p>La mayoría de las funciones producen un error cuando el tipo de datos que esperan no coincide con los que pasamos como argumentos. En esta situación seguiremos el siguiente camino:</p>
<ul>
<li><p>Comprobar el tipo de datos utilizando las funciones <code>is.*()</code>, que nos responden con un valor lógico (TRUE si el tipo de dato coincide y FALSE si no lo hace). Si el tipo de dato coincide con el formato esperado por el argumento de la función, entonces podemos aplicarla, de lo contrario necesitaremos continuar:</p></li>
<li><p>Forzar el tipo de datos deseado coercionando con funciones de la familia <code>as.*()</code>, que fuerzan el tipo de datos, siempre y cuando esto devuelva valores correctos. Por ejemplo, no podremos obtener valores correctos si intento coercionar caracteres a tipos numéricos.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ejmeplo coercionando la variable sexo de caracter a factor</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">as.factor</span>(datos<span class="sc">$</span>sexo) <span class="co"># llamamos a la variable con el formato &lt;dataframe&gt;$&lt;variable&gt;</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] M    M    M    M    M    M    M    M    &lt;NA&gt; F    F    M    F    F    F   
[16] F    F    M    M    M    M    M    M    F    M    F    &lt;NA&gt; M    F    M   
[31] F    F    M    F    F    F    M    M    M    M    M    F    M    F    M   
[46] M    F    M    F    &lt;NA&gt; M    M    M    F    M    M    M    M    M    F   
[61] F    M    F    F    M    M    F    F    F    M    M    M    M    M   
Levels: F M</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># detecta que hay dos niveles o categorías posibles (F y M) </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(<span class="fu">as.factor</span>(datos<span class="sc">$</span>sexo))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nos confirma que los datos se coercionaron a factor</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Transformar el tipo de dato a partir de aplicar funciones específicas incluidas en paquetes que gestionan datos especiales, como por ejemplo las fechas (el paquete <em>lubridate</em> del tidyverse, que conoceremos más adelante, se ocupa de esto)</li>
</ul>
<p>A continuación se muestra una lista con los tipos más importantes que se pueden comprobar o forzar a partir de funciones de R base:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tipo</th>
<th>Comprobación</th>
<th>Coerción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>character</td>
<td><code>is.character()</code></td>
<td><code>as.character()</code></td>
</tr>
<tr class="even">
<td>numeric</td>
<td><code>is.numeric()</code></td>
<td><code>as.numeric()</code></td>
</tr>
<tr class="odd">
<td>integer</td>
<td><code>is.integer()</code></td>
<td><code>as.integer()</code></td>
</tr>
<tr class="even">
<td>double</td>
<td><code>is.double()</code></td>
<td><code>as.double()</code></td>
</tr>
<tr class="odd">
<td>factor</td>
<td><code>is.factor()</code></td>
<td><code>as.factor()</code></td>
</tr>
<tr class="even">
<td>logical</td>
<td><code>is.logical()</code></td>
<td><code>as.logical()</code></td>
</tr>
<tr class="odd">
<td>NA</td>
<td><code>is.na()</code></td>
<td><code>as.na()</code></td>
</tr>
</tbody>
</table>
</section>
<section id="skimr" class="level2">
<h2 class="anchored" data-anchor-id="skimr">Skimr</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/03/skimr.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:10.0%"></p>
</figure>
</div>
<p>Existen diversas herramientas y funciones que facilitan la etapa de diagnóstico de datos, es el caso de skimr.</p>
<p>Este paquete tiene funciones diseñadas para obtener un resumen rápido de la estructura de tablas de datos y son compatibles con el ecosistema tidyverse.</p>
<p>La función principal del paquete es <code>skim</code> y puede ser aplicada a todo el dataframe o bien a una variable o a un grupo de ellas.</p>
<ul>
<li><p>Proporciona un conjunto más amplio de estadísticas que <code>summary()</code>, incluyendo valores faltantes, completos, número total (n) y desvío estándar (sd).</p></li>
<li><p>Informa de cada tipo de dato por separado.</p></li>
<li><p>Maneja fechas, valores lógicos y otros tipos.</p></li>
</ul>
<p>Trabajemos con <strong>skimr</strong> sobre un conjunto de datos provenientes de la vigilancia del SNVS.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(datos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">datos</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">200</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">56</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">47</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Date</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="even">
<td style="text-align: left;">logical</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 32%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">SEXO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">GRUPEDAD</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PROVINCIA_RESIDENCIA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ID_PROV_INDEC_RESIDENCIA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DEPARTAMENTO_RESIDENCIA</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ID_DEPTO_INDEC_RESIDENCIA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LOCALIDAD_RESIDENCIA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ESTABLECIMIENTO_SALUD</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">125</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ESTABLECIMIENTO_CARGA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">117</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">PROVINCIA_CARGA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DEPTO_CARGA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ESTAB_CLINICA</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DEPTO_CLINICA</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">PPL</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SERVICIO_PENITENCIARIO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">MOTIVO_CONSULTA</td>
<td style="text-align: right;">181</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CLASIFICACION_MANUAL</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">CLASIF_INICIO_TRAT</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ID_PULMONAR</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ID_EXTRAPULMONAR</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RESULTADO_RX</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bacteriologia</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Baciloscopia</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cultivo</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PRUEBA_RESISTENCIA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">RESISTENCIA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Droga</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tipo_Resistencia</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ESTABLECIMIENTO_MUESTRA</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">DEPARTAMENTO_MUESTRA</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ESTABLECIMIENTO_DIAG</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">DEPARTAMENTO_DIAG</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prueba_VIH</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">VIH</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TRATAMIENTO_ANTIRRETROVIRAL</td>
<td style="text-align: right;">199</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Diag_rapido</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Resultado_diag_rapido</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">EMBARAZO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">DIABETES</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">CONSUMO_PROB_DROGAS</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ENF_RESP_CRONICA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">COVID</td>
<td style="text-align: right;">199</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SE_DECLARA_PUEBLO_INDIGENA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">TABAQUISMO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ALCOHOLISMO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">ESTAB_TTO</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RESULTADO_TRATAMIENTO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: Date</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 24%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">min</th>
<th style="text-align: left;">max</th>
<th style="text-align: left;">median</th>
<th style="text-align: right;">n_unique</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FECHA_NACIMIENTO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">1934-12-13</td>
<td style="text-align: left;">2023-05-05</td>
<td style="text-align: left;">1989-07-27</td>
<td style="text-align: right;">198</td>
</tr>
<tr class="even">
<td style="text-align: left;">FECHA_APERTURA</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">2021-09-20</td>
<td style="text-align: left;">2024-04-18</td>
<td style="text-align: left;">2023-07-16</td>
<td style="text-align: right;">151</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FECHA_NOTIFICACION</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">2023-01-03</td>
<td style="text-align: left;">2023-12-27</td>
<td style="text-align: left;">2023-07-03</td>
<td style="text-align: right;">147</td>
</tr>
<tr class="even">
<td style="text-align: left;">FIS</td>
<td style="text-align: right;">48</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: left;">2020-12-20</td>
<td style="text-align: left;">2023-12-21</td>
<td style="text-align: left;">2023-05-12</td>
<td style="text-align: right;">116</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FECHA_INICIO_SINTOMA</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: left;">2022-08-15</td>
<td style="text-align: left;">2023-12-26</td>
<td style="text-align: left;">2023-05-17</td>
<td style="text-align: right;">116</td>
</tr>
<tr class="even">
<td style="text-align: left;">FECHA_INICIO_TRAT</td>
<td style="text-align: right;">43</td>
<td style="text-align: right;">0.78</td>
<td style="text-align: left;">2023-01-03</td>
<td style="text-align: left;">2024-01-08</td>
<td style="text-align: left;">2023-07-02</td>
<td style="text-align: right;">119</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FECHA_FIN_TRAT</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">0.29</td>
<td style="text-align: left;">2023-03-09</td>
<td style="text-align: left;">2024-04-05</td>
<td style="text-align: left;">2023-10-23</td>
<td style="text-align: right;">52</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: logical</strong></p>
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: left;">count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">ETNIA</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NaN</td>
<td style="text-align: left;">:</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 17%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">EDAD_DIAGNOSTICO</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">37.02</td>
<td style="text-align: right;">18.63</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">88</td>
<td style="text-align: left;">▂▇▅▃▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>La salida completa de <code>skim()</code> separa los resultados por partes. Un resumen de datos inicial, donde vemos la cantidad de filas y columnas con la frecuencia de tipo de variable. Luego le siguen tablas con información descriptiva univariada, donde podemos ver que dependiendo del tipo de variable nos muestra diferentes estadísticos y hasta un mini histograma en el caso de las numéricas.</p>
</section>
<section id="dlookr" class="level2">
<h2 class="anchored" data-anchor-id="dlookr">dlookr</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/03/dlookr.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:20.0%"></p>
</figure>
</div>
<p>El paquete se define como una <em>“colección de herramientas que permiten el diagnóstico, la exploración y la transformación de datos”</em>.</p>
<p>El diagnóstico de datos proporciona información y visualización de valores faltantes, valores atípicos y valores únicos y negativos para ayudarle a comprender la distribución y la calidad de sus datos.</p>
<p>Contiene funciones, compatibles con tidyverse, que nos facilitan ver la calidad de nuestros datos, además de otras que tienen por objetivo la exploración y su transformación.</p>
<p>Entre estas funciones encontramos:</p>
<section id="diagnose" class="level3">
<h3 class="anchored" data-anchor-id="diagnose">diagnose()</h3>
<p>Permite diagnosticar variables del dataframe y devuelve como resultado: el tipo de dato de la variable, la cantidad de valores faltantes, su porcentaje, la cantidad de valores únicos y su tasa (valores únicos/observaciones). Lo observamos en forma de tabla interactiva:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dlookr)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">diagnose</span>(datos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 56 × 6
   variables        types missing_count missing_percent unique_count unique_rate
   &lt;chr&gt;            &lt;chr&gt;         &lt;int&gt;           &lt;dbl&gt;        &lt;int&gt;       &lt;dbl&gt;
 1 SEXO             char…             0             0              3        0.01
 2 FECHA_NACIMIENTO Date              0             0            198        0.99
 3 EDAD_DIAGNOSTICO nume…             0             0             71        0.36
 4 GRUPEDAD         char…             0             0             18        0.09
 5 PROVINCIA_RESID… char…             0             0             18        0.09
 6 ID_PROV_INDEC_R… char…             0             0             18        0.09
 7 DEPARTAMENTO_RE… char…             9             4.5           82        0.41
 8 ID_DEPTO_INDEC_… char…             0             0             89        0.44
 9 LOCALIDAD_RESID… char…             0             0            106        0.53
10 ESTABLECIMIENTO… char…             0             0            125        0.62
# ℹ 46 more rows</code></pre>
</div>
</div>
<p>Al ser compatible con tidyverse se puede editar antes o después de la función, por ejemplo si quisiéramos filtrar variables con valores faltantes (de mayor a menor):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diagnose</span>(datos) <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">!</span><span class="fu">starts_with</span>(<span class="st">"unique"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(missing_count <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(missing_count))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 4
   variables                   types     missing_count missing_percent
   &lt;chr&gt;                       &lt;chr&gt;             &lt;int&gt;           &lt;dbl&gt;
 1 ETNIA                       logical             200           100  
 2 TRATAMIENTO_ANTIRRETROVIRAL character           199            99.5
 3 COVID                       character           199            99.5
 4 MOTIVO_CONSULTA             character           181            90.5
 5 FECHA_FIN_TRAT              Date                142            71  
 6 ESTABLECIMIENTO_DIAG        character            76            38  
 7 DEPARTAMENTO_DIAG           character            76            38  
 8 ESTABLECIMIENTO_MUESTRA     character            72            36  
 9 DEPARTAMENTO_MUESTRA        character            72            36  
10 FIS                         Date                 48            24  
11 FECHA_INICIO_SINTOMA        Date                 44            22  
12 FECHA_INICIO_TRAT           Date                 43            21.5
13 ESTAB_TTO                   character            35            17.5
14 ESTAB_CLINICA               character            20            10  
15 DEPTO_CLINICA               character            20            10  
16 DEPARTAMENTO_RESIDENCIA     character             9             4.5</code></pre>
</div>
</div>
</section>
<section id="diagnose_category" class="level3">
<h3 class="anchored" data-anchor-id="diagnose_category">diagnose_category()</h3>
<p>Así como existe <code>diagnose()</code> como una función general, también hay funciones que sirven para el diagnóstico específico por tipo de dato.</p>
<p><code>diagnose_category()</code> lo hace con las variables categóricas, es decir de caracter, de factor y de factor ordenado, mostrando información de cada categoría de cada variable (N, frecuencia, proporción y ranking).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">|&gt;</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">diagnose_category</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 296 × 6
   variables levels     N  freq ratio  rank
   &lt;chr&gt;     &lt;chr&gt;  &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;int&gt;
 1 SEXO      M        200   131  65.5     1
 2 SEXO      F        200    68  34       2
 3 SEXO      A        200     1   0.5     3
 4 GRUPEDAD  20-24    200    26  13       1
 5 GRUPEDAD  30-34    200    26  13       1
 6 GRUPEDAD  25-29    200    23  11.5     3
 7 GRUPEDAD  40-44    200    16   8       4
 8 GRUPEDAD  45-49    200    16   8       4
 9 GRUPEDAD  15-19    200    15   7.5     6
10 GRUPEDAD  35-39    200    15   7.5     6
# ℹ 286 more rows</code></pre>
</div>
</div>
</section>
<section id="diagnose_numeric" class="level3">
<h3 class="anchored" data-anchor-id="diagnose_numeric">diagnose_numeric()</h3>
<p>Para variables numéricas tenemos a <code>diagnose_numeric()</code> que nos brinda estadísticos resumen descriptivos univariados.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">|&gt;</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">diagnose_numeric</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 10
  variables          min    Q1  mean median    Q3   max  zero minus outlier
  &lt;chr&gt;            &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt;   &lt;int&gt;
1 EDAD_DIAGNOSTICO     0    23  37.0     33    49    88     3     0       0</code></pre>
</div>
</div>
<p>Observamos que sobre la única variable numérica de datos nos calcula el mínimo, primer cuartil, media, mediana, tercer cuartil, máximo, la cantidad de ceros, la cantidad de números negativos y la cantidad de datos atípicos.</p>
</section>
</section>
<section id="diagnose_outlier" class="level2">
<h2 class="anchored" data-anchor-id="diagnose_outlier">diagnose_outlier()</h2>
<p>Sobre los datos atípicos <code>diagnose_outlier()</code> nos amplía la información:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">diagnose_outlier</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  variables     outliers_cnt outliers_ratio outliers_mean with_mean without_mean
  &lt;chr&gt;                &lt;int&gt;          &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
1 EDAD_DIAGNOS…            0              0           NaN      37.0         37.0</code></pre>
</div>
</div>
<p>Aquí la variable EDAD_DIAGNOSTICO no tiene datos atípicos por lo que el conteo y proporción es de cero, la media de los outlier no existe y la media contando y no contando estos outlier da lo mismo (37,02)</p>
</section>
<section id="plot_outlier" class="level2">
<h2 class="anchored" data-anchor-id="plot_outlier">plot_outlier()</h2>
<p>Agreguemos algún dato atípico a EDAD_DIAGNOSTICO para poder mostrar este gráfico.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>datos[<span class="dv">10</span>, <span class="st">"EDAD_DIAGNOSTICO"</span>] <span class="ot">&lt;-</span> <span class="dv">105</span>  <span class="co"># cambiamos la edad de la observación 10 </span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">plot_outlier</span>(EDAD_DIAGNOSTICO) </span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.
ℹ The deprecated feature was likely used in the dlookr package.
  Please report the issue at &lt;https://github.com/choonghyunryu/dlookr/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="unidad3_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:120.0%"></p>
</figure>
</div>
</div>
</div>
<p>El gráfico siempre se va a producir si al menos tenemos un dato atípico en la variable. Grafica un boxplot e histograma contando los valores outlier que la variable tenga y otro quitándolos.</p>
<section id="otras-funciones-del-paquete" class="level3">
<h3 class="anchored" data-anchor-id="otras-funciones-del-paquete">Otras funciones del paquete</h3>
<p><strong>dlookr</strong> tiene muchas otras funciones, para la conversión de datos y/o la imputación de datos ausentes, que no trabajaremos en el curso pero pueden encontrarse en el sitio del desarrollador <a href="https://choonghyunryu.github.io/dlookr/index.html" class="uri">https://choonghyunryu.github.io/dlookr/index.html</a></p>
</section>
</section>
<section id="depuración-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="depuración-de-datos">Depuración de datos</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/03/datacleaning.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
<p>Una vez finalizado el diagnóstico de datos, se procede a la etapa de depuración, donde se corrigen los errores identificados y se prepara el conjunto de datos para su análisis. La depuración involucra técnicas como la eliminación de valores faltantes, la corrección de errores de entrada, la transformación de variables y el manejo de valores atípicos.</p>
<p>Un flujo de trabajo modelo partiendo de datos crudos y terminando en datos limpios es el siguiente:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/03/flujo.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
<p>Durante este proceso puede haber múltiples situaciones dependiendo de la calidad original de los datos crudos, desde carecer de encabezados o contener tipos de datos incorrectos, pasando por tener que corregir etiquetas de categorías incorrectas, etc.</p>
<p>Las herramientas de <strong>dplyr</strong> en tidyverse nos van a facilitar esta tarea que suele ocupar entre un 70 y 80% del tiempo de trabajo cuando analizamos datos.</p>
</section>
<section id="gestión-de-duplicados" class="level2">
<h2 class="anchored" data-anchor-id="gestión-de-duplicados">Gestión de duplicados</h2>
<p>Un caso habitual con el que debemos lidiar es el tener observaciones duplicadas, total o parcialmente. Por este motivo, debemos conocer las características de la o las tablas con las que estamos trabajando, es decir, si las observaciones tiene claves unívocas, si estas observaciones se pueden repetir, si la relación es uno a uno o uno a varios cuando hay más de una tabla relacionada, etc.</p>
<p>Entonces, el primer paso será asegurarnos que los datos cumplen con el criterio que conocemos haciendo una detección de observaciones y/o partes de observaciones (variables clave) que se encuentran duplicadas.</p>
<p>Luego, hay diferentes tareas que se pueden realizar para gestionar estos datos duplicados, cuando su existencia no es la esperada:</p>
<ul>
<li><p>Eliminación de duplicados a partir de observaciones únicas.</p></li>
<li><p>Recortar tabla de datos para eliminar duplicados</p></li>
<li><p>Marcar duplicados (conservando duplicados en la tabla)</p></li>
</ul>
<p>La función <code>get_dupes()</code> del paquete <strong>janitor</strong> es muy útil porque identifica estas repeticiones.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dupes</span>(<span class="fu">everything</span>())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 57
# ℹ 57 variables: SEXO &lt;chr&gt;, FECHA_NACIMIENTO &lt;date&gt;, EDAD_DIAGNOSTICO &lt;dbl&gt;,
#   GRUPEDAD &lt;chr&gt;, PROVINCIA_RESIDENCIA &lt;chr&gt;, ID_PROV_INDEC_RESIDENCIA &lt;chr&gt;,
#   DEPARTAMENTO_RESIDENCIA &lt;chr&gt;, ID_DEPTO_INDEC_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;date&gt;, …</code></pre>
</div>
</div>
<p>Aplicada sobre el dataframe entero detecta aquellas observaciones que sean iguales en todas sus observaciones. Esto es difícil que pase pero puede suceder cuando por alguna falla técnica el sistema desde donde se obtienen los datos duplica registros completos.</p>
<p>Otra posibilidad es utilizar la variable que es clave en la tabla de datos o las variables que constituyen una clave combinada.</p>
<p>Por ejemplo, en este caso, usemos una serie de variables como SEXO, FECHA_NACIMIENTO, ID_PROV_INDEC_RESIDENCIA e ID_DEPTO_INDEC_RESIDENCIA para ver si hay observaciones donde estos datos se repitan.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dupes</span>(SEXO, FECHA_NACIMIENTO, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>            ID_PROV_INDEC_RESIDENCIA, ID_DEPTO_INDEC_RESIDENCIA)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 57
  SEXO  FECHA_NACIMIENTO ID_PROV_INDEC_RESIDENCIA ID_DEPTO_INDEC_RESIDENCIA
  &lt;chr&gt; &lt;date&gt;           &lt;chr&gt;                    &lt;chr&gt;                    
1 M     1947-06-29       90                       90063                    
2 M     1947-06-29       90                       90063                    
# ℹ 53 more variables: dupe_count &lt;int&gt;, EDAD_DIAGNOSTICO &lt;dbl&gt;,
#   GRUPEDAD &lt;chr&gt;, PROVINCIA_RESIDENCIA &lt;chr&gt;, DEPARTAMENTO_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;date&gt;,
#   FECHA_NOTIFICACION &lt;date&gt;, MOTIVO_CONSULTA &lt;chr&gt;, …</code></pre>
</div>
</div>
<p>Encontramos dos observaciones que tienen los mismo valores en esta combinación de variables. Un hombre nacido el 29/06/1947 en la provincia de Tucumán, en el departamento Lules.</p>
<p>Supongamos que no puede existir dos veces la misma persona en la tabla (sería deseable confirmar esto teniendo alguna variable univoca cómo el DNI, por ejemplo), procederíamos a solucionar este duplicado.</p>
<section id="eliminación-de-duplicados-por-observaciones-únicas" class="level3">
<h3 class="anchored" data-anchor-id="eliminación-de-duplicados-por-observaciones-únicas">Eliminación de duplicados por observaciones únicas</h3>
<p>Para eliminar filas duplicadas en una tabla de datos podemos utilizar la función <code>distinct()</code> de <strong>dplyr</strong>.</p>
<p>La función tiene un argumento denominado <code>.keep_all</code> que permite valores <em>TRUE</em> o <em>FALSE</em>. Si se iguala a <em>TRUE</em> se mantienen en el resultado todas las variables que son parte de la tabla, aunque estas no estén declaradas dentro del <code>distinct()</code>.</p>
<p>Por defecto, este argumento se encuentra igualado a <em>FALSE</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(datos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 200</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(SEXO, FECHA_NACIMIENTO, ID_PROV_INDEC_RESIDENCIA, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>           ID_DEPTO_INDEC_RESIDENCIA, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">.keep_all =</span> T)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 199 × 56
   SEXO  FECHA_NACIMIENTO EDAD_DIAGNOSTICO GRUPEDAD PROVINCIA_RESIDENCIA
   &lt;chr&gt; &lt;date&gt;                      &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;               
 1 M     1948-06-22                     74 70-74    Tierra del Fuego    
 2 F     1981-06-20                     41 40-44    Buenos Aires        
 3 F     1989-03-30                     33 30-34    Buenos Aires        
 4 M     2006-11-17                     16 15-19    Chaco               
 5 M     1993-06-02                     29 25-29    Jujuy               
 6 M     1989-04-08                     33 30-34    Buenos Aires        
 7 F     1977-07-30                     45 45-49    Buenos Aires        
 8 M     1968-04-09                     54 50-54    Misiones            
 9 F     2008-01-10                     15 15-19    Chaco               
10 M     1987-11-27                    105 35-39    Buenos Aires        
# ℹ 189 more rows
# ℹ 51 more variables: ID_PROV_INDEC_RESIDENCIA &lt;chr&gt;,
#   DEPARTAMENTO_RESIDENCIA &lt;chr&gt;, ID_DEPTO_INDEC_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;date&gt;, …</code></pre>
</div>
</div>
<p>Observamos que las 200 observaciones <code>distinct()</code> nos devuelve 199. Eliminó una de las dos que tenían duplicadas esa serie de variables definidas (no podemos controlar cuál de ellas elimina).</p>
</section>
<section id="eliminación-de-duplicados-por-recorte-de-observaciones" class="level3">
<h3 class="anchored" data-anchor-id="eliminación-de-duplicados-por-recorte-de-observaciones">Eliminación de duplicados por recorte de observaciones</h3>
<p>Recortar es similar a filtrar, la diferencia está en que se filtra por condiciones y recortamos por posiciones.</p>
<p>La familia de funciones de <strong>dplyr</strong> que se puede utilizar para recortar es <code>slice_*()</code>.</p>
<p>Estas funciones pueden ser muy útiles si se aplican a un dataframe agrupado porque la operación de recorte se realiza en cada grupo por separado.</p>
<p>Por ejemplo, podemos usar la FECHA_NOTIFICACION para seleccionar la mas vieja. Esto se hace combinado <code>group_by()</code> y <code>slice_min()</code> (observación con el valor mínimo)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dupes</span>(SEXO, FECHA_NACIMIENTO, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>             ID_PROV_INDEC_RESIDENCIA, ID_DEPTO_INDEC_RESIDENCIA) <span class="sc">|&gt;</span> </span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEXO, FECHA_NACIMIENTO, FECHA_NOTIFICACION)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  SEXO  FECHA_NACIMIENTO FECHA_NOTIFICACION
  &lt;chr&gt; &lt;date&gt;           &lt;date&gt;            
1 M     1947-06-29       2023-03-10        
2 M     1947-06-29       2023-02-24        </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(SEXO, FECHA_NACIMIENTO, </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>           ID_PROV_INDEC_RESIDENCIA, ID_DEPTO_INDEC_RESIDENCIA) <span class="sc">|&gt;</span> </span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(FECHA_NOTIFICACION) <span class="sc">|&gt;</span> </span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SEXO <span class="sc">==</span> <span class="st">"M"</span>, FECHA_NACIMIENTO <span class="sc">==</span> <span class="fu">dmy</span>(<span class="st">"29/06/1947"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SEXO, FECHA_NACIMIENTO, FECHA_NOTIFICACION) <span class="sc">|&gt;</span> </span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Adding missing grouping variables: `ID_PROV_INDEC_RESIDENCIA`,
`ID_DEPTO_INDEC_RESIDENCIA`</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
  ID_PROV_INDEC_RESIDENCIA ID_DEPTO_INDEC_RESIDENCIA SEXO  FECHA_NACIMIENTO
  &lt;chr&gt;                    &lt;chr&gt;                     &lt;chr&gt; &lt;date&gt;          
1 90                       90063                     M     1947-06-29      
# ℹ 1 more variable: FECHA_NOTIFICACION &lt;date&gt;</code></pre>
</div>
</div>
</section>
<section id="marcar-duplicados" class="level3">
<h3 class="anchored" data-anchor-id="marcar-duplicados">Marcar duplicados</h3>
<p>Si, en cambio, lo que buscamos es mantener a todas las observaciones de la tabla pero marcar aquellos que consideramos duplicados podemos hacer:</p>
<ol type="1">
<li><p>Recortar el dataframe original a sólo las filas para el análisis. Guardar los ID de este dataframe reducido en un vector.</p></li>
<li><p>En el dataframe original, creamos una variable de marca usando una función condicional, basándonos si el ID está presente en el dataframe reducido (vector de ID anterior).</p></li>
</ol>
<p>Primer paso, en esta tabla no existe un ID único por lo que vamos a crear una clave subrogada.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">|&gt;</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ID =</span> <span class="fu">row_number</span>())</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Ahora usaremos este ID para crear un vector con los números de las dos observaciones anteriores que están duplicadas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>ID_duplicados <span class="ot">&lt;-</span> datos <span class="sc">|&gt;</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dupes</span>(SEXO, FECHA_NACIMIENTO, </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>             ID_PROV_INDEC_RESIDENCIA, ID_DEPTO_INDEC_RESIDENCIA) <span class="sc">|&gt;</span> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(ID)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>ID_duplicados</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  44 166</code></pre>
</div>
</div>
<p>Finalmente aplicamos este vector con una función como <code>if_else()</code> para marcar con una <strong>X</strong> en la variable duplicado.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">|&gt;</span> </span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">duplicado =</span> <span class="fu">if_else</span>(ID <span class="sc">%in%</span> ID_duplicados, <span class="st">"X"</span>, <span class="cn">NA</span>))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Luego podriamos filtrar los duplicados directamente</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(duplicado <span class="sc">==</span> <span class="st">"X"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 58
  SEXO  FECHA_NACIMIENTO EDAD_DIAGNOSTICO GRUPEDAD PROVINCIA_RESIDENCIA
  &lt;chr&gt; &lt;date&gt;                      &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;               
1 M     1947-06-29                     75 75-79    Tucumán             
2 M     1947-06-29                     75 75-79    Tucumán             
# ℹ 53 more variables: ID_PROV_INDEC_RESIDENCIA &lt;chr&gt;,
#   DEPARTAMENTO_RESIDENCIA &lt;chr&gt;, ID_DEPTO_INDEC_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;date&gt;,
#   FECHA_NOTIFICACION &lt;date&gt;, MOTIVO_CONSULTA &lt;chr&gt;, …</code></pre>
</div>
</div>
</section>
</section>
<section id="datos-faltantes-o-perdidos" class="level2">
<h2 class="anchored" data-anchor-id="datos-faltantes-o-perdidos">Datos faltantes o perdidos</h2>
<p>Cuando trabajamos con datos los valores perdidos o faltantes (conocidos en inglés como <em>missing</em>) pueden constituir un serio problema en nuestras variables por lo que deben explorarse y manejarse cuidadosamente en las etapas iniciales del análisis.</p>
<p>Estos datos pueden faltar por muchas razones, pero generalmente se suelen agrupar en dos categorías: valores faltantes informativos y valores faltantes aleatorios. Los informativos implican una causa estructural, ya sea por deficiencias en la forma en que se recopilaron los datos o por anomalías en el entorno de observación. Los aleatorios son aquellos que tienen lugar independientemente del proceso de recopilación de datos.</p>
<p>Dependiendo de si los valores faltantes son de uno u otro tipo, se procederá de una u otra manera. A los informativos, en general, se les puede asignar un valor concreto (por ejemplo, “Ninguno” o “Sin dato”), ya que este valor puede convenir tenerlo como una categoría más de la variable. Los aleatorios, en cambio, pueden manejarse mediante la eliminación o la imputación.</p>
<p>Resumiendo, las tareas habituales respecto a estos valores consisten en:</p>
<ul>
<li>Evaluar la existencia de valores perdidos (exploración y conteo).</li>
<li>Excluir los valores ausentes (si es posible y conveniente).</li>
<li>Etiquetar o recodificar los valores ausentes (imputación de datos).</li>
</ul>
<p>Respecto a la imputación existen numerosa bibliografía sobre diversos algoritmos que no vamos a incluir en este curso.</p>
</section>
<section id="detectar-observaciones-incompletas-valores-missing" class="level2">
<h2 class="anchored" data-anchor-id="detectar-observaciones-incompletas-valores-missing">Detectar observaciones incompletas (valores missing)</h2>
<p>El lenguaje R gestiona a los datos perdidos mediante el valor especial reservado <code>NA</code> de <strong>Not Available</strong> (No disponible),</p>
<p>En principio, sólo vamos a enfocarnos en como podemos utilizar algunas funciones del lenguaje para detectarlos y contabilizarlos. A partir de su identificación decidiremos que hacer con ellos, dependiendo de su cantidad y extensión, es decir, si los valores faltantes son la mayoría de una variable o la mayoría de una observación o bien si representan la falta de respuesta de una pregunta, con lo cual convenga etiquetarlos.</p>
<p>Una manera de abordar esta tarea con R base para una variables es hacer la sumatoria de valores <code>NA</code>, usando la función de identificación <code>is.na()</code>.</p>
<p>Para ejemplificar, tomamos una tabla de datos de vigilancia con 200 observaciones y 56 variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Cantidad_NA =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(FECHA_FIN_TRAT)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  Cantidad_NA
        &lt;int&gt;
1         142</code></pre>
</div>
</div>
<p>La consulta dice que hay 142 observaciones vacías en la variable FECHA_FIN_TRAT. Lo malo es que debemos hacer esta tarea variable por variable, lo que resulta muy trabajoso.</p>
<p>También la función <code>summary()</code> aplicada sobre el dataframe completo informa la cantidad de <code>NA</code> de variables cuantitativas, lógicas y fecha, pero no lo hace con las de tipo caracter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(datos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     SEXO           FECHA_NACIMIENTO     EDAD_DIAGNOSTICO   GRUPEDAD        
 Length:200         Min.   :1934-12-13   Min.   :  0.00   Length:200        
 Class :character   1st Qu.:1973-11-06   1st Qu.: 23.00   Class :character  
 Mode  :character   Median :1989-07-27   Median : 33.00   Mode  :character  
                    Mean   :1985-12-04   Mean   : 37.37                     
                    3rd Qu.:1999-11-17   3rd Qu.: 49.00                     
                    Max.   :2023-05-05   Max.   :105.00                     
                                                                            
 PROVINCIA_RESIDENCIA ID_PROV_INDEC_RESIDENCIA DEPARTAMENTO_RESIDENCIA
 Length:200           Length:200               Length:200             
 Class :character     Class :character         Class :character       
 Mode  :character     Mode  :character         Mode  :character       
                                                                      
                                                                      
                                                                      
                                                                      
 ID_DEPTO_INDEC_RESIDENCIA LOCALIDAD_RESIDENCIA ESTABLECIMIENTO_SALUD
 Length:200                Length:200           Length:200           
 Class :character          Class :character     Class :character     
 Mode  :character          Mode  :character     Mode  :character     
                                                                     
                                                                     
                                                                     
                                                                     
 ESTABLECIMIENTO_CARGA PROVINCIA_CARGA    DEPTO_CARGA        ESTAB_CLINICA     
 Length:200            Length:200         Length:200         Length:200        
 Class :character      Class :character   Class :character   Class :character  
 Mode  :character      Mode  :character   Mode  :character   Mode  :character  
                                                                               
                                                                               
                                                                               
                                                                               
 DEPTO_CLINICA          PPL            SERVICIO_PENITENCIARIO
 Length:200         Length:200         Length:200            
 Class :character   Class :character   Class :character      
 Mode  :character   Mode  :character   Mode  :character      
                                                             
                                                             
                                                             
                                                             
 FECHA_APERTURA       FECHA_NOTIFICACION   MOTIVO_CONSULTA   
 Min.   :2021-09-20   Min.   :2023-01-03   Length:200        
 1st Qu.:2023-04-12   1st Qu.:2023-04-03   Class :character  
 Median :2023-07-16   Median :2023-07-03   Mode  :character  
 Mean   :2023-07-14   Mean   :2023-07-01                     
 3rd Qu.:2023-10-18   3rd Qu.:2023-10-03                     
 Max.   :2024-04-18   Max.   :2023-12-27                     
                                                             
 CLASIFICACION_MANUAL CLASIF_INICIO_TRAT ID_PULMONAR       
 Length:200           Length:200         Length:200        
 Class :character     Class :character   Class :character  
 Mode  :character     Mode  :character   Mode  :character  
                                                           
                                                           
                                                           
                                                           
      FIS             ID_EXTRAPULMONAR   FECHA_INICIO_SINTOMA
 Min.   :2020-12-20   Length:200         Min.   :2022-08-15  
 1st Qu.:2023-02-20   Class :character   1st Qu.:2023-03-01  
 Median :2023-05-12   Mode  :character   Median :2023-05-17  
 Mean   :2023-05-10                      Mean   :2023-05-28  
 3rd Qu.:2023-08-09                      3rd Qu.:2023-08-09  
 Max.   :2023-12-21                      Max.   :2023-12-26  
 NA's   :48                              NA's   :44          
 RESULTADO_RX       Bacteriologia      Baciloscopia         Cultivo         
 Length:200         Length:200         Length:200         Length:200        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
 PRUEBA_RESISTENCIA RESISTENCIA           Droga           Tipo_Resistencia  
 Length:200         Length:200         Length:200         Length:200        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
                                                                            
 ESTABLECIMIENTO_MUESTRA DEPARTAMENTO_MUESTRA ESTABLECIMIENTO_DIAG
 Length:200              Length:200           Length:200          
 Class :character        Class :character     Class :character    
 Mode  :character        Mode  :character     Mode  :character    
                                                                  
                                                                  
                                                                  
                                                                  
 DEPARTAMENTO_DIAG   Prueba_VIH            VIH           
 Length:200         Length:200         Length:200        
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 TRATAMIENTO_ANTIRRETROVIRAL Diag_rapido        Resultado_diag_rapido
 Length:200                  Length:200         Length:200           
 Class :character            Class :character   Class :character     
 Mode  :character            Mode  :character   Mode  :character     
                                                                     
                                                                     
                                                                     
                                                                     
   EMBARAZO           DIABETES         CONSUMO_PROB_DROGAS ENF_RESP_CRONICA  
 Length:200         Length:200         Length:200          Length:200        
 Class :character   Class :character   Class :character    Class :character  
 Mode  :character   Mode  :character   Mode  :character    Mode  :character  
                                                                             
                                                                             
                                                                             
                                                                             
    COVID           SE_DECLARA_PUEBLO_INDIGENA  ETNIA        
 Length:200         Length:200                 Mode:logical  
 Class :character   Class :character           NA's:200      
 Mode  :character   Mode  :character                         
                                                             
                                                             
                                                             
                                                             
  TABAQUISMO        ALCOHOLISMO         ESTAB_TTO         FECHA_INICIO_TRAT   
 Length:200         Length:200         Length:200         Min.   :2023-01-03  
 Class :character   Class :character   Class :character   1st Qu.:2023-03-20  
 Mode  :character   Mode  :character   Mode  :character   Median :2023-07-02  
                                                          Mean   :2023-06-28  
                                                          3rd Qu.:2023-10-05  
                                                          Max.   :2024-01-08  
                                                          NA's   :43          
 FECHA_FIN_TRAT       RESULTADO_TRATAMIENTO       ID          duplicado        
 Min.   :2023-03-09   Length:200            Min.   :  1.00   Length:200        
 1st Qu.:2023-08-21   Class :character      1st Qu.: 50.75   Class :character  
 Median :2023-10-23   Mode  :character      Median :100.50   Mode  :character  
 Mean   :2023-10-23                         Mean   :100.50                     
 3rd Qu.:2024-01-11                         3rd Qu.:150.25                     
 Max.   :2024-04-05                         Max.   :200.00                     
 NA's   :142                                                                   </code></pre>
</div>
</div>
<p>Más completo y en una sola línea la función <code>find_na()</code> del paquete <strong>dlookr</strong> muestra el porcentaje de valores perdidos en todas las variables de una tabla de datos y se complementa con el gráfico de barras de pareto <code>plot_na_pareto()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dlookr)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">find_na</span>(datos, <span class="at">rate =</span> T) <span class="co"># argumento rate = T muestra % de valores NA</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       SEXO            FECHA_NACIMIENTO 
                        0.0                         0.0 
           EDAD_DIAGNOSTICO                    GRUPEDAD 
                        0.0                         0.0 
       PROVINCIA_RESIDENCIA    ID_PROV_INDEC_RESIDENCIA 
                        0.0                         0.0 
    DEPARTAMENTO_RESIDENCIA   ID_DEPTO_INDEC_RESIDENCIA 
                        4.5                         0.0 
       LOCALIDAD_RESIDENCIA       ESTABLECIMIENTO_SALUD 
                        0.0                         0.0 
      ESTABLECIMIENTO_CARGA             PROVINCIA_CARGA 
                        0.0                         0.0 
                DEPTO_CARGA               ESTAB_CLINICA 
                        0.0                        10.0 
              DEPTO_CLINICA                         PPL 
                       10.0                         0.0 
     SERVICIO_PENITENCIARIO              FECHA_APERTURA 
                        0.0                         0.0 
         FECHA_NOTIFICACION             MOTIVO_CONSULTA 
                        0.0                        90.5 
       CLASIFICACION_MANUAL          CLASIF_INICIO_TRAT 
                        0.0                         0.0 
                ID_PULMONAR                         FIS 
                        0.0                        24.0 
           ID_EXTRAPULMONAR        FECHA_INICIO_SINTOMA 
                        0.0                        22.0 
               RESULTADO_RX               Bacteriologia 
                        0.0                         0.0 
               Baciloscopia                     Cultivo 
                        0.0                         0.0 
         PRUEBA_RESISTENCIA                 RESISTENCIA 
                        0.0                         0.0 
                      Droga            Tipo_Resistencia 
                        0.0                         0.0 
    ESTABLECIMIENTO_MUESTRA        DEPARTAMENTO_MUESTRA 
                       36.0                        36.0 
       ESTABLECIMIENTO_DIAG           DEPARTAMENTO_DIAG 
                       38.0                        38.0 
                 Prueba_VIH                         VIH 
                        0.0                         0.0 
TRATAMIENTO_ANTIRRETROVIRAL                 Diag_rapido 
                       99.5                         0.0 
      Resultado_diag_rapido                    EMBARAZO 
                        0.0                         0.0 
                   DIABETES         CONSUMO_PROB_DROGAS 
                        0.0                         0.0 
           ENF_RESP_CRONICA                       COVID 
                        0.0                        99.5 
 SE_DECLARA_PUEBLO_INDIGENA                       ETNIA 
                        0.0                       100.0 
                 TABAQUISMO                 ALCOHOLISMO 
                        0.0                         0.0 
                  ESTAB_TTO           FECHA_INICIO_TRAT 
                       17.5                        21.5 
             FECHA_FIN_TRAT       RESULTADO_TRATAMIENTO 
                       71.0                         0.0 
                         ID                   duplicado 
                        0.0                        99.0 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_na_pareto</span>(datos, </span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">only_na =</span> T) <span class="co"># argumento only_na = T muestra variables solo con algún valor NA </span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
ℹ The deprecated feature was likely used in the dlookr package.
  Please report the issue at &lt;https://github.com/choonghyunryu/dlookr/issues&gt;.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="unidad3_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" style="width:120.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="gestión-de-nas-con-naniar" class="level2">
<h2 class="anchored" data-anchor-id="gestión-de-nas-con-naniar">Gestión de NA’s con naniar</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/03/naniar.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:15.0%"></p>
</figure>
</div>
<p>El paquete <strong>naniar</strong> es un paquete que reúne funciones diseñadas para el manejo de valores faltantes pensado para una gestión completa.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'naniar'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:skimr':

    n_complete</code></pre>
</div>
</div>
<p>Sus caracteristicas generales son:</p>
<ul>
<li><p>Proporciona funciones analíticas y visuales de detección y gestión</p></li>
<li><p>Es compatible con el mundo “tidy” de tidyverse</p></li>
<li><p>Aborda las relaciones o estructura de la falta de datos.</p></li>
<li><p>Posibilita el trabajo de imputación (no tratado en este curso)</p></li>
</ul>
<p>De las muchas funciones que tiene el paquete seleccionamos algunas para mostrar que son muy útiles para una tarea básica.</p>
<p>La función <code>miss_var_summary()</code> proporciona un resumen sobre los valores NA en cada variable del dataframe similar a <code>find_na()</code> que vimos anterioremente pero con una salida en forma de tabla y un recento absoluto, además de porcentual.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_var_summary</span>(datos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 58 × 3
   variable                    n_miss pct_miss
   &lt;chr&gt;                        &lt;int&gt;    &lt;num&gt;
 1 ETNIA                          200    100  
 2 TRATAMIENTO_ANTIRRETROVIRAL    199     99.5
 3 COVID                          199     99.5
 4 duplicado                      198     99  
 5 MOTIVO_CONSULTA                181     90.5
 6 FECHA_FIN_TRAT                 142     71  
 7 ESTABLECIMIENTO_DIAG            76     38  
 8 DEPARTAMENTO_DIAG               76     38  
 9 ESTABLECIMIENTO_MUESTRA         72     36  
10 DEPARTAMENTO_MUESTRA            72     36  
# ℹ 48 more rows</code></pre>
</div>
</div>
<p>Por el lado gráfico, ofrece la función <code>gg_miss_var()</code> que representa la información de la tabla anterior pero a través de un gráfico <em>lollipop</em> horizontal de tipo <strong>ggplot2</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_var</span>(datos, </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">show_pct =</span> T) <span class="co"># muestra valores en porcentajes</span></span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="unidad3_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" style="width:120.0%"></p>
</figure>
</div>
</div>
</div>
<p>Hay otra viaulización muy interesante porque muestra las relaciones de los valores ausentes de las variables cuya función se llama <code>gg_miss_upset()</code> y genera un gráfico <strong>Upset</strong> en función de la existencia de valores NA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_miss_upset</span>(datos) </span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><img src="images/03/upset1.png" class="img-fluid"> Por defecto, construye el gráfico tomando las primeras 10 variables de la tabla de datos con valores NA de forma decreciente. Esto se puede modificar cambiando el argumentos <code>nset =</code>.</p>
<p>Tiene dos entradas para su lectura. En la parte inferior izquierda nos muestra los nombres de las variables con valores NA ordenadas de menor a mayor medida en una escala absoluta. El gráfico de barras principal, ordenado de forma predeterminada de mayor a menor, informa sobre las cantidades absolutas de valores NA de las combinaciones que aperecen debajo del eje x del gráfico.</p>
<p>Por ejemplo, la variable ETNIA tiene todos sus observaciones como NA y la variable COVID casi lo mismo, mientras que la variable FIS cerca de 50.</p>
<p>Podemos eliminar del gráfico a esas dos variables con casi todos los valores NA, usando formas de tidyverse previas dado que las funciones de naniar son compatibles.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>ETNIA, <span class="sc">-</span>COVID) <span class="sc">|&gt;</span> </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gg_miss_upset</span>() </span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><img src="images/03/upset2.png" class="img-fluid"></p>
<p>Al quitar esas dos variables, aparecen dos nuevas con cantidades menores de NA que FIS (FECHA_INICIO_TRAT y FECHA_INICIO_SINTOMA), es decir siguen siendo 10 por defecto.</p>
<p>Si miramos los datos faltantes con estructura notamos que la combinación más frecuente de NA combinados es FECHA_FIN_TRAT, MOTIVO_CONSULTA y TRATAMIENTO_ANTIRETROVIRAL con 39 observaciones a las que le faltan valores en las tres variables simultáneamente.</p>
</section>
<section id="reemplazo-de-valores" class="level2">
<h2 class="anchored" data-anchor-id="reemplazo-de-valores">Reemplazo de valores</h2>
<p>El paquete tiene además dos funciones de reemplazo que funcionan como herramientas antagónicas.</p>
<p><code>replace_with_na()</code> reemplaza valores o etiquetas específicas con valores NA y <code>replace_na_with()</code> hace lo contrario, reemplaza valores NA con valores específicos, como “Sin dato” por ejemplo.</p>
<p>La primera función trabaja sobre el dataframe completo adignando valores NA en la categoría o valor que le indiquemos.</p>
<p>Por ejemplo, la variable ID_PROV_INDEC_RESIDENCIA no tiene valores perdidos pero si hay una categoría/código desconocido (“00”), entonces podemos decirle que ese código sea NA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Cantidad_NA =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(ID_PROV_INDEC_RESIDENCIA)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  Cantidad_NA
        &lt;int&gt;
1           0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">replace_with_na</span>(<span class="at">replace =</span> <span class="fu">list</span>(<span class="at">ID_PROV_INDEC_RESIDENCIA =</span> <span class="st">"00"</span>)) <span class="sc">|&gt;</span>     </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Cantidad_NA =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(ID_PROV_INDEC_RESIDENCIA)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  Cantidad_NA
        &lt;int&gt;
1           2</code></pre>
</div>
</div>
<p><code>replace_na_with()</code> etiqueta valores faltantes con categorías definidas que serán tenidas en cuenta a la hora de hacer tablas u otras operaciones. Esta función se utiliza dentro de <code>mutate()</code> del tidyverse.</p>
<p>La variable MOTIVO_CONSULTA tiene 181 valores NA que serán etiquetados como “Sin dato” de esta forma:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(MOTIVO_CONSULTA)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  MOTIVO_CONSULTA              n
  &lt;chr&gt;                    &lt;int&gt;
1 Contacto                     2
2 Examen de Salud              1
3 Sintomático Respiratorio    16
4 &lt;NA&gt;                       181</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MOTIVO_CONSULTA =</span> <span class="fu">replace_na_with</span>(MOTIVO_CONSULTA, </span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>                                           <span class="st">"Sin dato"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(MOTIVO_CONSULTA)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  MOTIVO_CONSULTA              n
  &lt;chr&gt;                    &lt;int&gt;
1 Contacto                     2
2 Examen de Salud              1
3 Sin dato                   181
4 Sintomático Respiratorio    16</code></pre>
</div>
</div>
</section>
<section id="eliminación-de-valores-na" class="level2">
<h2 class="anchored" data-anchor-id="eliminación-de-valores-na">Eliminación de valores NA</h2>
<p>Cuando decidimos eliminar valores NA de alguna variable, salvo que se quite la variable entera, tenemos que tener en cuenta que perdemos la observación completa, incluso valores válidos que se encuentran en otras variables.</p>
<p>R base tiene una función llamada <code>na.omit()</code> que omite toda observación donde al menos haya un solo NA en alguna variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">na.omit</span>(datos)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 58
# ℹ 58 variables: SEXO &lt;chr&gt;, FECHA_NACIMIENTO &lt;date&gt;, EDAD_DIAGNOSTICO &lt;dbl&gt;,
#   GRUPEDAD &lt;chr&gt;, PROVINCIA_RESIDENCIA &lt;chr&gt;, ID_PROV_INDEC_RESIDENCIA &lt;chr&gt;,
#   DEPARTAMENTO_RESIDENCIA &lt;chr&gt;, ID_DEPTO_INDEC_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;date&gt;, …</code></pre>
</div>
</div>
<p>Aplicar esta función sobre el dataframe datos produce que no quede ninguna observación, dado que vimos que la variable ETNIA tenía sus doscientos valores vacíos.</p>
<p>Una función superadora es <code>drop_na()</code> de tidyr que pertenece a tidyverse, porque omite observaciones que tengan variables que definamos, por ejemplo:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(ETNIA)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 58
# ℹ 58 variables: SEXO &lt;chr&gt;, FECHA_NACIMIENTO &lt;date&gt;, EDAD_DIAGNOSTICO &lt;dbl&gt;,
#   GRUPEDAD &lt;chr&gt;, PROVINCIA_RESIDENCIA &lt;chr&gt;, ID_PROV_INDEC_RESIDENCIA &lt;chr&gt;,
#   DEPARTAMENTO_RESIDENCIA &lt;chr&gt;, ID_DEPTO_INDEC_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;date&gt;, …</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">|&gt;</span> </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(FIS)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 152 × 58
   SEXO  FECHA_NACIMIENTO EDAD_DIAGNOSTICO GRUPEDAD PROVINCIA_RESIDENCIA
   &lt;chr&gt; &lt;date&gt;                      &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;               
 1 M     1948-06-22                     74 70-74    Tierra del Fuego    
 2 F     1981-06-20                     41 40-44    Buenos Aires        
 3 F     1989-03-30                     33 30-34    Buenos Aires        
 4 M     2006-11-17                     16 15-19    Chaco               
 5 M     1993-06-02                     29 25-29    Jujuy               
 6 M     1989-04-08                     33 30-34    Buenos Aires        
 7 F     1977-07-30                     45 45-49    Buenos Aires        
 8 F     2008-01-10                     15 15-19    Chaco               
 9 M     1987-11-27                    105 35-39    Buenos Aires        
10 F     2002-12-21                     20 20-24    Buenos Aires        
# ℹ 142 more rows
# ℹ 53 more variables: ID_PROV_INDEC_RESIDENCIA &lt;chr&gt;,
#   DEPARTAMENTO_RESIDENCIA &lt;chr&gt;, ID_DEPTO_INDEC_RESIDENCIA &lt;chr&gt;,
#   LOCALIDAD_RESIDENCIA &lt;chr&gt;, ESTABLECIMIENTO_SALUD &lt;chr&gt;,
#   ESTABLECIMIENTO_CARGA &lt;chr&gt;, PROVINCIA_CARGA &lt;chr&gt;, DEPTO_CARGA &lt;chr&gt;,
#   ESTAB_CLINICA &lt;chr&gt;, DEPTO_CLINICA &lt;chr&gt;, PPL &lt;chr&gt;,
#   SERVICIO_PENITENCIARIO &lt;chr&gt;, FECHA_APERTURA &lt;date&gt;, …</code></pre>
</div>
</div>
<p>En el ejemplo anterior aplicamos la función sobre la variable ETNIA y FIS, en el primer caso omite todas las observaciones y en el segundo caso 48 observaciones, mostrando las 152 restantes sin NA en la variable.</p>
<p>Por último, debemos saber que eliminar observaciones por valores faltantes reduce la potencia de cualquier test de hipotesis o modelo que hagamos porque se reduce el tamaño de la muestra.</p>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Volver arriba</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>